### PR TITLE
Emotion Icons v3

### LINKED ISSUE #216: Not support yet for @emotion 11 version
Hello. I was just accidentally using @emotion 11 version and it was the latest released just 14 days ago.

When I tried to use your package, I encountered the issue saying `Can't resolve '@emotion/styled-base'`.
I think this is related to the pr below.
https://github.com/emotion-js/emotion/pull/1575
`@emotion/styled-base` was moved to `@emotion/styled/base`.

I don't know how to support it so I just want to how contributors will deal with this issue by watching :) Thanks for reading

### PR DESCRIPTION
**Pull request by JoshRosenstein**
PR to support Emotion 11.

closes #216

### CODE REVIEW

**Comment by JoshRosenstein** [comment]
@jacobwgillespie When you get a change can you take a look at Vercel deployment details. The link does not work for me.

**Comment by jacobwgillespie** [comment]
@JoshRosenstein thank you for getting this PR going! 🎉 

I've made a few changes, but have not yet solved the build error. First, the changes:

1. I reverted your commits that updated the version to 3.0.0 - that's something that `changesets` will do automatically, and I think it would have actually tried to release 4.0 if we'd updated the version manually in this PR (as a plus, it'll figure out all the places that need to be updated)
2. I removed a header in the changeset file - `changesets` will already be adding that exact header 👍 
3. We're now using `@emotion/babel-plugin`

So the build error is this:

```
TypeError: Cannot read property 'type' of null
    at Array.compat (/Users/jacobwgillespie/Code/emotion-icons/emotion-icons/node_modules/@emotion/cache/dist/emotion-cache.cjs.prod.js:44:163)
    at /Users/jacobwgillespie/Code/emotion-icons/emotion-icons/node_modules/@emotion/cache/node_modules/stylis/dist/umd/stylis.js:1:6503
    at re (/Users/jacobwgillespie/Code/emotion-icons/emotion-icons/node_modules/@emotion/cache/node_modules/stylis/dist/umd/stylis.js:1:6197)
    at Array.ae (/Users/jacobwgillespie/Code/emotion-icons/emotion-icons/node_modules/@emotion/cache/node_modules/stylis/dist/umd/stylis.js:1:6368)
    at /Users/jacobwgillespie/Code/emotion-icons/emotion-icons/node_modules/@emotion/cache/node_modules/stylis/dist/umd/stylis.js:1:6503
    at Object.re [as serialize] (/Users/jacobwgillespie/Code/emotion-icons/emotion-icons/node_modules/@emotion/cache/node_modules/stylis/dist/umd/stylis.js:1:6197)
    at getRules (/Users/jacobwgillespie/Code/emotion-icons/emotion-icons/node_modules/@emotion/cache/dist/emotion-cache.cjs.prod.js:122:14)
    at Object._insert [as insert] (/Users/jacobwgillespie/Code/emotion-icons/emotion-icons/node_modules/@emotion/cache/dist/emotion-cache.cjs.prod.js:125:43)
    at /Users/jacobwgillespie/Code/emotion-icons/emotion-icons/node_modules/@emotion/react/dist/emotion-react.cjs.prod.js:87:58
    at /Users/jacobwgillespie/Code/emotion-icons/emotion-icons/node_modules/@emotion/react/dist/emotion-element-3a01c80e.cjs.prod.js:27:8
```

You can reproduce locally if you'd like (note the `SMALL=1` environment variable, which only adds 10 icons per pack, this vastly speeds things up for local debugging):

```bash
$ yarn clean
$ SMALL=1 yarn build
```

After at least one `yarn build`, you can also `cd website && yarn start` to get the website dev server, which also has the same error.

This is _probably_ related to the Emotion 11 upgrade. I can't find any GitHub issues that look related, but if I get some more time I'll do some digging unless you or someone figures it out first. 🙂

**Comment by JoshRosenstein** [comment]
@jacobwgillespie  thanks for that! and yeah sorry, not quite familiar with changesets. I had to tweak the main tasks in order to build locally on windows. After doing so, it took me a while but found the weird bug that was causing the issue. Not sure what the underlying reason is.. all I know is that Emotion 11 was not liking this style block.https://github.com/emotion-icons/emotion-icons/blob/ce938aec4d80819b9a1960bcda7b8f6d95ba3ce3/website/src/components/Layout.tsx#L168-L175
But for some reason, it compiled fine within its own component.

**Comment by jacobwgillespie** [comment]
Nice find!

I believe I found the Storybook fix, apparently `@emotion/styled` v11 doesn't work with Storybook without some patching, tracking issue here: https://github.com/storybookjs/storybook/issues/12262. I've applied the hack solution for now.

**Comment by jacobwgillespie** [comment]
Nice, everything built! I think we can merge this PR, then I'll follow up with a PR to upgrade the icon dependencies so that everything's clean for v3 (I'll open this PR now against this branch but retarget it after this merges)

**Review by jacobwgillespie — APPROVED** [review]
Thank you for this, super awesome! 🎉

**Pull request merged**
